openapi: 3.0.0
info:
  title: Fin Tech API - Tranjaction Management
  description: This API provides the Tranjaction Management operations.
  version: 0.0.1

components:
  securitySchemes:
    bearerAuth:
      type: http
      description: Provide auth token , recieved from cisl OAuth service to access all api's.
      scheme: bearer
      bearerFormat: "bearer"  # optional, for documentation purposes only
security:
  - bearerAuth: [ ]

paths:
  /fintech/tranjaction/update-account-balance:
    post:
      summary: update account balance based on tranjaction
      operationId: updateAccountBalance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'fintech-models.yml#/components/schemas/TranjactionDetailsDTO'
      responses:
        '200':
          description: updated account details
          content:
            application/json:
              schema:
                $ref: 'fintech-models.yml#/components/schemas/TranjactionDetailsDTO'
      tags:
        - Tranjaction Management